### ISSUE TITLE
Not able to run the tool

### ISSUE THREAD

**Issue by jakobgetz** [miguelfbrito/microservice-identification#6]
Hi,
first of all the install script doesn't work for me, after some debugging I was able to run the tool in general with the `-h` option.
I run it inside a docker container here is the Dockerfile:
```
FROM ubuntu

WORKDIR /app
COPY . .

RUN apt update -y \
    && apt install software-properties-common -y \
    && add-apt-repository ppa:deadsnakes/ppa -y \
    && apt install python3-pip -y \
    && cd app \
    && pip3 install sklearn \
    && pip3 install kneed \
    && pip3 install matplotlib \
    && pip3 install networkx \
    && pip3 install javalang \
    && pip3 install gensim \
    && pip3 install pyLDAvis==2.1.2 \
    && pip3 install community \
    && pip3 install karateclub \
    && pip3 install nltk \
    && pip3 install stop_words \
    && pip3 install multipledispatch

WORKDIR /app/app
```

I tried to run the tool with jpetstore-6 (just the repo cloned from GitHub), it is also present in the docker container.
Running  `python3 app/main.py -p jpetstore-6` returns the following error:
```
Setting Directory as: /
Invoking parsing: java -Dparse -Dproject=app/jpetstore-6 -Dstop_words=//stop_words.txt -cp symbolsolver-1.0.jar Main
Traceback (most recent call last):
  File "/app/app/main.py", line 373, in <module>
    main()
  File "/app/app/main.py", line 315, in main
    clusters_results = identify_clusters_in_project(
  File "/app/app/main.py", line 245, in identify_clusters_in_project
    utils.execute_parser(project_path)
  File "/app/app/Utils.py", line 15, in execute_parser
    subprocess.call(command, cwd=symbol_solver_path, shell=True)
  File "/usr/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '//symbolsolver/target/'
```

Do you know what is wrong here.

**Comment by miguelfbrito** [comment]
Hey, please try the https://github.com/miguelfbrito/microservice-identification/tree/develop branch and let me know if it works.

**Comment by jakobgetz** [comment]
Ive build the image again with the development branch. I also extended the install script of the docker file to install mallet as well.
```
FROM ubuntu

WORKDIR /app
COPY . .

RUN path="$PWD" \
    && apt update -y \
    && apt install git -y \
    && apt install software-properties-common -y \
    && add-apt-repository ppa:deadsnakes/ppa -y \
    && apt install python3-pip -y \
    && cd app \
    && pip3 install sklearn \
    && pip3 install kneed \
    && pip3 install matplotlib \
    && pip3 install networkx \
    && pip3 install javalang \
    && pip3 install gensim \
    && pip3 install pyLDAvis==2.1.2 \
    && pip3 install community \
    && pip3 install karateclub \
    && pip3 install nltk \
    && pip3 install stop_words \
    && pip3 install multipledispatch \
    && JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8 \
    && apt install ant -y \
    && git clone https://github.com/mimno/Mallet.git ~/.mallet \
    && cd ~/.mallet \
    && ant \
    && cd "$path" \
    # Install Maven and build
    && cd symbolsolver \
    && apt install maven -y \
    && mvn package -DskipTests
```
It still returns the exact same error.
